"use client";

import { useRouter } from "next/navigation";
import "./globals.css";
import Cookies from "js-cookie";
import { useEffect } from "react";
import isNil from "lodash/isNil";
import Link from "next/link";
// import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const sessionKey = Cookies.get("session_key");
  const router = useRouter();

  useEffect(() => {
    if (isNil(sessionKey)) {
      router.push("/login");
    }
  }, []);

  return (
    <html lang="en">
      <body>
        <nav>
          <Link href="/settings/contexts">Contexts</Link>
          <Link href="/settings/imap">IMAP Settings</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
