# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import vector_grpc.vector_services_pb2 as vector__services__pb2


class VectorServiceStub(object):
    """The service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Fit = channel.unary_unary(
                '/vector_analysis.VectorService/Fit',
                request_serializer=vector__services__pb2.FitRequest.SerializeToString,
                response_deserializer=vector__services__pb2.Empty.FromString,
                )
        self.Transform = channel.unary_unary(
                '/vector_analysis.VectorService/Transform',
                request_serializer=vector__services__pb2.TransformRequest.SerializeToString,
                response_deserializer=vector__services__pb2.VectorResponse.FromString,
                )
        self.Load = channel.unary_unary(
                '/vector_analysis.VectorService/Load',
                request_serializer=vector__services__pb2.Empty.SerializeToString,
                response_deserializer=vector__services__pb2.Empty.FromString,
                )


class VectorServiceServicer(object):
    """The service definition.
    """

    def Fit(self, request, context):
        """Sends a VectorRequest and gets a VectorResponse
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Transform(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Load(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VectorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Fit': grpc.unary_unary_rpc_method_handler(
                    servicer.Fit,
                    request_deserializer=vector__services__pb2.FitRequest.FromString,
                    response_serializer=vector__services__pb2.Empty.SerializeToString,
            ),
            'Transform': grpc.unary_unary_rpc_method_handler(
                    servicer.Transform,
                    request_deserializer=vector__services__pb2.TransformRequest.FromString,
                    response_serializer=vector__services__pb2.VectorResponse.SerializeToString,
            ),
            'Load': grpc.unary_unary_rpc_method_handler(
                    servicer.Load,
                    request_deserializer=vector__services__pb2.Empty.FromString,
                    response_serializer=vector__services__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vector_analysis.VectorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class VectorService(object):
    """The service definition.
    """

    @staticmethod
    def Fit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vector_analysis.VectorService/Fit',
            vector__services__pb2.FitRequest.SerializeToString,
            vector__services__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Transform(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vector_analysis.VectorService/Transform',
            vector__services__pb2.TransformRequest.SerializeToString,
            vector__services__pb2.VectorResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Load(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vector_analysis.VectorService/Load',
            vector__services__pb2.Empty.SerializeToString,
            vector__services__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
