# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vector_services.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15vector_services.proto\x12\x0fvector_analysis\":\n\nFitRequest\x12,\n\x07vectors\x18\x01 \x03(\x0b\x32\x1b.vector_analysis.FloatArray\"T\n\x10TransformRequest\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12,\n\x07vectors\x18\x02 \x03(\x0b\x32\x1b.vector_analysis.FloatArray\">\n\x0eVectorResponse\x12,\n\x07vectors\x18\x01 \x03(\x0b\x32\x1b.vector_analysis.FloatArray\"\x07\n\x05\x45mpty\"\x1c\n\nFloatArray\x12\x0e\n\x06values\x18\x01 \x03(\x02\x32\xda\x01\n\rVectorService\x12<\n\x03\x46it\x12\x1b.vector_analysis.FitRequest\x1a\x16.vector_analysis.Empty\"\x00\x12Q\n\tTransform\x12!.vector_analysis.TransformRequest\x1a\x1f.vector_analysis.VectorResponse\"\x00\x12\x38\n\x04Load\x12\x16.vector_analysis.Empty\x1a\x16.vector_analysis.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vector_services_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_FITREQUEST']._serialized_start=42
  _globals['_FITREQUEST']._serialized_end=100
  _globals['_TRANSFORMREQUEST']._serialized_start=102
  _globals['_TRANSFORMREQUEST']._serialized_end=186
  _globals['_VECTORRESPONSE']._serialized_start=188
  _globals['_VECTORRESPONSE']._serialized_end=250
  _globals['_EMPTY']._serialized_start=252
  _globals['_EMPTY']._serialized_end=259
  _globals['_FLOATARRAY']._serialized_start=261
  _globals['_FLOATARRAY']._serialized_end=289
  _globals['_VECTORSERVICE']._serialized_start=292
  _globals['_VECTORSERVICE']._serialized_end=510
# @@protoc_insertion_point(module_scope)
